---
abstract: 'introspection for roles'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Modern: 0.006
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Role-Inspector
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Role::Inspector:
    file: lib/Role/Inspector.pm
    version: 0.001
requires:
  Exporter::Shiny: 0
  Module::Runtime: 0
  Scalar::Util: 0
  perl: 5.006
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Role-Inspector/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Role-Inspector
  homepage: https://metacpan.org/release/Role-Inspector
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-role-inspector.git
version: 0.001
